name: PR Settings

on:
  pull_request:
    types: [opened]

jobs:
  pr-settings:
    runs-on: ubuntu-latest
    steps:
      - name: PR Settings
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            }) 